openapi: 3.0.4
info:
  description: This service api give access to documents
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Snapshot service
  version: 1.0.0
servers:
- url: http://localhost:8080/v1
tags:
- description: Объявление (о покупке или продаже)
  name: snapshot
paths:
  /document/read:
    post:
      operationId: readSnapshot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapshotReadRequest'
        description: Request body
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotReadResponse'
          description: Success
      summary: Method to read snapshot
      tags:
      - Read
      x-content-type: application/json
      x-accepts: application/json
  /document/search:
    post:
      operationId: searchSnapshot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapshotSearchRequest'
        description: request for search snapshot by filename
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotSearchResponse'
          description: Success
      summary: Method to search snapshot with parameters
      tags:
      - Search
      x-content-type: application/json
      x-accepts: application/json
  /document/list:
    post:
      operationId: listOfSnapshots
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SnapshotListRequest'
        description: request for search snapshot by filename
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapshotListResponse'
          description: Success
      summary: Get list of all available snapshots
      tags:
      - List of available snapshots
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    IRequest:
      description: Базовый интерфейс для всех запросов
      discriminator:
        mapping:
          read: '#/components/schemas/SnapshotReadRequest'
          search: '#/components/schemas/SnapshotSearchRequest'
          list: '#/components/schemas/SnapshotListRequest'
        propertyName: requestType
      properties:
        requestType:
          description: Поле-дескриминатор для вычисления типа запроса
          type: string
        requestId:
          description: Идентификатор запроса для отладки и идемпотентности
          type: string
      type: object
    SnapshotReadRequest:
      allOf:
      - $ref: '#/components/schemas/IRequest'
      - $ref: '#/components/schemas/SnapshotRequestDebug'
      - $ref: '#/components/schemas/SnapshotReadRequest_allOf'
    SnapshotSearchRequest:
      allOf:
      - $ref: '#/components/schemas/IRequest'
      - $ref: '#/components/schemas/SnapshotRequestDebug'
      - $ref: '#/components/schemas/SnapshotSearchRequest_allOf'
    SnapshotListRequest:
      allOf:
      - $ref: '#/components/schemas/IRequest'
      - $ref: '#/components/schemas/SnapshotRequestDebug'
    SnapshotSearchFilter:
      description: Поиск файла по части названия
      properties:
        searchString:
          description: поиска списка по части названия
          type: string
      type: object
    SnapshotReadObject:
      allOf:
      - $ref: '#/components/schemas/SnapshotReadObject_allOf'
    Error:
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string
      type: object
    ResponseResult:
      enum:
      - success
      - error
      type: string
    IResponse:
      description: Базовый интерфейс для всех ответов
      discriminator:
        mapping:
          read: '#/components/schemas/SnapshotReadResponse'
          search: '#/components/schemas/SnapshotSearchResponse'
          list: '#/components/schemas/SnapshotListResponse'
        propertyName: responseType
      properties:
        responseType:
          description: Поле-дескриминатор для вычисления типа запроса
          example: read
          type: string
        requestId:
          description: Идентификатор запроса для отладки
          type: string
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          items:
            $ref: '#/components/schemas/Error'
          type: array
      type: object
    SnapshotReadResponse:
      allOf:
      - $ref: '#/components/schemas/IResponse'
      - $ref: '#/components/schemas/SnapshotResponseObject'
    SnapshotSearchResponse:
      allOf:
      - $ref: '#/components/schemas/IResponse'
      - $ref: '#/components/schemas/SnapshotSearchResponse_allOf'
    SnapshotListResponse:
      allOf:
      - $ref: '#/components/schemas/IResponse'
      - $ref: '#/components/schemas/SnapshotListObject'
    SnapshotResponseObject:
      description: Данные снапшота указанного пользователем
      properties:
        metadata:
          $ref: '#/components/schemas/SnapshotMetaDateObject'
        snapshot:
          description: Данные snapshot
          type: string
        permissions:
          items:
            $ref: '#/components/schemas/SnapshotPermissions'
          type: array
          uniqueItems: true
      type: object
    SnapshotJsonObject:
      description: Данные snapshot
      type: string
    SnapshotListObject:
      allOf:
      - $ref: '#/components/schemas/SnapshotListObject_allOf'
    SnapshotMetaDateObject:
      properties:
        id:
          description: Идентификатор объявления
          type: string
        userId:
          description: Идентификатор объявления
          type: string
      type: object
    SnapshotId:
      description: Идентификатор объявления
      type: string
    UserId:
      description: Идентификатор объявления
      type: string
    SnapshotDate:
      description: Дата снапшота
      format: date
      type: string
    SnapshotName:
      description: Имя файла из которого загрузился снапшот
      type: string
    SnapshotRequestDebug:
      properties:
        debug:
          $ref: '#/components/schemas/SnapshotDebug'
      type: object
    SnapshotDebug:
      properties:
        mode:
          $ref: '#/components/schemas/SnapshotRequestDebugMode'
        stub:
          $ref: '#/components/schemas/SnapshotRequestDebugStubs'
      type: object
    SnapshotRequestDebugMode:
      enum:
      - prod
      - test
      - stub
      type: string
    SnapshotRequestDebugStubs:
      description: Перечисления всех стабов
      enum:
      - success
      - notFound
      - badId
      - badTitle
      - badDescription
      - badVisibility
      - cannotDelete
      - badSearchString
      type: string
    SnapshotPermissions:
      description: Доступы для клиента для
      enum:
      - public
      - private
      type: string
    SnapshotReadRequest_allOf:
      properties:
        snapshot:
          $ref: '#/components/schemas/SnapshotReadObject'
      type: object
      example: null
    SnapshotSearchRequest_allOf:
      properties:
        snapshot:
          $ref: '#/components/schemas/SnapshotSearchFilter'
      type: object
      example: null
    SnapshotReadObject_allOf:
      properties:
        id:
          description: Идентификатор объявления
          type: string
      type: object
      example: null
    SnapshotSearchResponse_allOf:
      description: список снапшотов
      properties:
        list:
          items:
            $ref: '#/components/schemas/SnapshotListObject'
          type: array
      type: object
      example: null
    SnapshotListObject_allOf:
      description: "Список файлов наименования, дата, тип и id"
      properties:
        id:
          description: Идентификатор объявления
          type: string
        userId:
          description: Идентификатор объявления
          type: string
        date:
          description: Дата снапшота
          format: date
          type: string
        name:
          description: Имя файла из которого загрузился снапшот
          type: string
      type: object
      example: null

